const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
ctx.imageSmoothingEnabled = false;

const CONFIG = Object.freeze({ width: canvas.width, height: canvas.height, groundY: 302, gravity: 1850, jumpVelocity: -690, speeds: [190, 280, 390], initialSpeedIndex: 1, tubeMinGap: 265, tubeMaxGap: 470, bulletSpeed: 610, shootCooldown: 0.22, dayNightSeconds: 18, scorePerSecond: 12, tubeScore: 80, maxDelta: 1 / 20 });
const PALETTES = { day:{sky:'#d8f3dc',dark:'#16324f',mid:'#2d6a4f',hot:'#f4a261'}, night:{sky:'#10233c',dark:'#f1fa8c',mid:'#ffb703',hot:'#ff4d6d'} };
const state={running:true,score:0,best:Number(localStorage.getItem('lab8.best')||0),elapsed:0,speedIndex:CONFIG.initialSpeedIndex,spawnDistance:330,worldDistance:0,tubes:[],bullets:[],particles:[],flash:0};
const guido={x:126,y:CONFIG.groundY-38,width:34,height:38,vy:0,grounded:true,shootTimer:0,runFrame:0};
const isNight=()=>Math.floor(state.elapsed/CONFIG.dayNightSeconds)%2===1; const palette=()=>isNight()?PALETTES.night:PALETTES.day; const currentSpeed=()=>CONFIG.speeds[state.speedIndex]; const rand=(a,b)=>a+Math.random()*(b-a);
function rectsOverlap(a,b,i=0){return a.x+i<b.x+b.width-i&&a.x+a.width-i>b.x+i&&a.y+i<b.y+b.height-i&&a.y+a.height-i>b.y+i}
function resetGame(){Object.assign(state,{running:true,score:0,elapsed:0,speedIndex:CONFIG.initialSpeedIndex,spawnDistance:330,worldDistance:0,flash:0});state.tubes.length=state.bullets.length=state.particles.length=0;Object.assign(guido,{y:CONFIG.groundY-guido.height,vy:0,grounded:true,shootTimer:0})}
function jump(){if(state.running&&guido.grounded){guido.vy=CONFIG.jumpVelocity;guido.grounded=false}} function shoot(){if(!state.running||guido.shootTimer>0)return;guido.shootTimer=CONFIG.shootCooldown;state.bullets.push({x:guido.x+guido.width-2,y:guido.y+15,width:10,height:4})} function changeSpeed(d){state.speedIndex=Math.max(0,Math.min(CONFIG.speeds.length-1,state.speedIndex+d))}
function handleAction(a){if(!state.running&&(a==='jump'||a==='shoot')){resetGame();return} if(a==='jump')jump();if(a==='shoot')shoot();if(a==='slower')changeSpeed(-1);if(a==='faster')changeSpeed(1)}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','w','x','f','+','=','-','_','r','enter'].includes(k))e.preventDefault();if(k===' '||k==='arrowup'||k==='w')handleAction('jump');else if(k==='x'||k==='f')handleAction('shoot');else if(k==='+'||k==='=')handleAction('faster');else if(k==='-'||k==='_')handleAction('slower');else if((k==='r'||k==='enter')&&!state.running)resetGame()});
function bindPressAction(button){const release=e=>{if(e)e.preventDefault();button.classList.remove('is-pressed')};button.addEventListener('pointerdown',e=>{e.preventDefault();button.classList.add('is-pressed');if(button.setPointerCapture)try{button.setPointerCapture(e.pointerId)}catch{}handleAction(button.dataset.action)});button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release);button.addEventListener('contextmenu',e=>e.preventDefault())} document.querySelectorAll('[data-action]').forEach(bindPressAction);
canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(!state.running)resetGame();else jump()});canvas.addEventListener('contextmenu',e=>e.preventDefault());['touchstart','touchmove','gesturestart','gesturechange'].forEach(n=>document.addEventListener(n,e=>{if(e.target.closest?.('.game-frame'))e.preventDefault()},{passive:false}));
function spawnTube(){const tall=Math.random()<.3,w=tall?30:26,h=tall?54:42;state.tubes.push({x:CONFIG.width+24,y:CONFIG.groundY-h,width:w,height:h,zombie:isNight(),wobble:Math.random()*Math.PI*2});state.spawnDistance=rand(CONFIG.tubeMinGap,CONFIG.tubeMaxGap);state.worldDistance=0}
function explode(x,y,color){for(let i=0;i<8;i++)state.particles.push({x,y,vx:rand(-110,110),vy:rand(-150,20),life:rand(.2,.45),size:Math.random()<.5?4:6,color})} function gameOver(){state.running=false;state.best=Math.max(state.best,Math.floor(state.score));localStorage.setItem('lab8.best',String(state.best));state.flash=.25}
function update(dt){state.flash=Math.max(0,state.flash-dt);guido.shootTimer=Math.max(0,guido.shootTimer-dt);state.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt});state.particles=state.particles.filter(p=>p.life>0);if(!state.running)return;state.elapsed+=dt;state.score+=CONFIG.scorePerSecond*dt*(.7+state.speedIndex*.35);state.worldDistance+=currentSpeed()*dt;guido.runFrame+=dt*(5+state.speedIndex*2);guido.vy+=CONFIG.gravity*dt;guido.y+=guido.vy*dt;const floor=CONFIG.groundY-guido.height;if(guido.y>=floor){guido.y=floor;guido.vy=0;guido.grounded=true}if(state.worldDistance>=state.spawnDistance)spawnTube();state.tubes.forEach(t=>{t.x-=currentSpeed()*dt;t.wobble+=dt*7});state.bullets.forEach(b=>b.x+=CONFIG.bulletSpeed*dt);state.tubes=state.tubes.filter(t=>t.x+t.width>-20);state.bullets=state.bullets.filter(b=>b.x<CONFIG.width+30);for(let bi=state.bullets.length-1;bi>=0;bi--){for(let ti=state.tubes.length-1;ti>=0;ti--){if(rectsOverlap(state.bullets[bi],state.tubes[ti],1)){const t=state.tubes[ti];explode(t.x+t.width/2,t.y+t.height/2,palette().hot);state.tubes.splice(ti,1);state.bullets.splice(bi,1);state.score+=CONFIG.tubeScore;break}}}const hit={x:guido.x+5,y:guido.y+4,width:guido.width-10,height:guido.height-5};for(const t of state.tubes)if(rectsOverlap(hit,t,2)){gameOver();break}}
function pxRect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function drawBackground(p){pxRect(0,0,CONFIG.width,CONFIG.height,p.sky);ctx.fillStyle=p.dark;for(let i=0;i<16;i++){const x=(i*83-(state.elapsed*currentSpeed()*.08))%(CONFIG.width+40),y=30+((i*47)%128);ctx.fillRect(Math.round(x),y,3,3)}ctx.fillStyle=p.mid;const o=-(state.elapsed*currentSpeed()*.16)%160;for(let x=o-160;x<CONFIG.width+160;x+=160){ctx.fillRect(Math.round(x),190,112,72);ctx.fillRect(Math.round(x+12),170,22,20);ctx.fillRect(Math.round(x+58),152,30,38);ctx.fillRect(Math.round(x+96),180,10,10)}pxRect(0,CONFIG.groundY,CONFIG.width,6,p.dark);for(let x=-((state.elapsed*currentSpeed())%32);x<CONFIG.width;x+=32)pxRect(x,CONFIG.groundY+12,18,4,p.mid)}
function drawGuido(p){const x=Math.round(guido.x),y=Math.round(guido.y),step=guido.grounded?Math.floor(guido.runFrame)%2:0;pxRect(x+15,y,4,6,p.hot);pxRect(x+18,y-3,4,4,p.hot);pxRect(x+7,y+6,21,16,p.mid);pxRect(x+4,y+21,26,11,p.dark);pxRect(x+10,y+11,4,4,p.sky);pxRect(x+21,y+11,4,4,p.sky);pxRect(x+28,y+22,9,5,p.hot);if(step===0){pxRect(x+8,y+32,6,6,p.mid);pxRect(x+22,y+32,6,6,p.mid)}else{pxRect(x+5,y+32,9,6,p.mid);pxRect(x+22,y+32,9,6,p.mid)}}
function drawTube(t,p){const x=Math.round(t.x),y=Math.round(t.y+Math.sin(t.wobble)*(t.zombie?1.5:0)),glass=t.zombie?p.hot:p.mid,liquid=t.zombie?p.mid:p.hot;pxRect(x+6,y,t.width-12,6,p.dark);pxRect(x+4,y+6,t.width-8,t.height-10,glass);pxRect(x+7,y+t.height-18,t.width-14,12,liquid);pxRect(x+7,y+t.height-6,t.width-14,4,p.dark);if(t.zombie){pxRect(x+8,y+15,5,4,p.sky);pxRect(x+t.width-13,y+15,5,4,p.sky);pxRect(x+11,y+26,t.width-22,4,p.dark);pxRect(x+3,y+24,5,9,p.hot);pxRect(x+t.width-8,y+21,5,10,p.hot)}}
function drawHud(p){ctx.fillStyle=p.dark;ctx.font='bold 18px monospace';ctx.textBaseline='top';ctx.fillText(`SCORE ${String(Math.floor(state.score)).padStart(6,'0')}`,20,16);ctx.fillText(`BEST ${String(state.best).padStart(6,'0')}`,20,40);const names=['LENTA','NORMALE','VELOCE'];ctx.textAlign='right';ctx.fillText(`MARCIA ${state.speedIndex+1}/3 ${names[state.speedIndex]}`,CONFIG.width-20,16);ctx.fillStyle=isNight()?p.hot:p.mid;ctx.fillText(isNight()?'NOTTE // ZOMBIE':'GIORNO // LAB',CONFIG.width-20,40);ctx.textAlign='left'}
function drawOverlay(p){if(state.running)return;ctx.fillStyle=`${p.sky}dd`;ctx.fillRect(180,108,600,140);ctx.strokeStyle=p.dark;ctx.lineWidth=4;ctx.strokeRect(180,108,600,140);ctx.fillStyle=p.dark;ctx.textAlign='center';ctx.font='bold 34px monospace';ctx.fillText('CONTAMINAZIONE!',CONFIG.width/2,138);ctx.font='bold 18px monospace';ctx.fillText(`PUNTEGGIO ${Math.floor(state.score)}  //  BEST ${state.best}`,CONFIG.width/2,185);ctx.font='16px monospace';ctx.fillText('R / INVIO / TAP PER RIPARTIRE',CONFIG.width/2,218);ctx.textAlign='left'}
function render(){const p=palette();drawBackground(p);state.tubes.forEach(t=>drawTube(t,p));state.bullets.forEach(b=>{pxRect(b.x,b.y,b.width,b.height,p.hot);pxRect(b.x+b.width,b.y+1,4,2,p.dark)});state.particles.forEach(q=>pxRect(q.x,q.y,q.size,q.size,q.color));drawGuido(p);drawHud(p);drawOverlay(p);if(state.flash>0){ctx.globalAlpha=state.flash*2.5;ctx.fillStyle=p.hot;ctx.fillRect(0,0,CONFIG.width,CONFIG.height);ctx.globalAlpha=1}}
let lastTime=performance.now();function loop(now){const dt=Math.min(CONFIG.maxDelta,(now-lastTime)/1000);lastTime=now;update(dt);render();requestAnimationFrame(loop)}canvas.focus();requestAnimationFrame(loop);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(error=>console.warn('LAB-8 service worker non disponibile:',error)));
